#this pipeline is for python API on Azure Kubernetes Services

name: Build CI

on: workflow_dispatch

# Below environment variables available to all jobs and steps in this workflow
env:
    REGISTRY_NAME: sai9356
    CONTAINER_NAME: test-image
    CLUSTER_NAME: my-aks-cluster
    CLUSTER_RESOURCE_GROUP: dinkar-rg
    NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

      # Connecting to Azure Container registry (ACR)
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Docker container build 
    - name: Docker Build
      run: |
        echo '<-----------------------Docker build started----------------------->'
        docker build . -t ${{ env.REGISTRY_NAME }}.jfrog.io/${{env.CONTAINER_NAME}}:${{ github.sha }}
        echo '<------------------------Docker build Ended------------------------>'

    - name: Docker Login
      run: |
        echo '<--------------- Docker Login --------------->'
        docker login valaxy01.jfrog.io -u ${{ secrets.ARTIFACTORY_USERNAME }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}
        echo '<--------------- Docker Login Ended --------------->'
     
    # Docker Container Push to ACR
    - name: Docker Push
      run: |
        echo '<-----------------------Docker Publish started----------------------->'
        docker push ${{ env.REGISTRY_NAME }}.jfrog.io/${{env.CONTAINER_NAME}}:${{ github.sha }}
        echo '<------------------------Docker Publish Ended------------------------>'
        
