#this pipeline is for python API on Azure Kubernetes Services

name: Build CI

on: push

# Below environment variables available to all jobs and steps in this workflow
env:
    REGISTRY_NAME: sai9356
    # CLUSTER_NAME: cluster-name
    # CLUSTER_RESOURCE_GROUP: cluster-resource-group
    # NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

      # Connecting to Azure Container registry (ACR)
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Docker container build 
    - name: Docker Build
      run: |
        echo '<-----------------------Docker build started----------------------->'
        cd /Docker
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/mytestimage:${{ github.sha }}
        echo '<------------------------Docker build Ended------------------------>'
    
    # Docker Container Push to ACR
    - name: Docker Push
      run: |
        echo '<-----------------------Docker Publish started----------------------->'
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/mytestimage:${{ github.sha }}
        echo '<------------------------Docker Publish Ended------------------------>'