#this pipeline is for python API on Azure Kubernetes Services
#docker build . -t ${{ env.ARTIFACTORY_NAME }}.jfrog.io/${{env.CONTAINER_NAME}}:${{ github.sha }}
#docker push ${{ env.ARTIFACTORY_NAME }}.jfrog.io/${{env.CONTAINER_NAME}}:${{ github.sha }}

name: Build CI

on: push

# Below environment variables available to all jobs and steps in this workflow
env:
  ARTIFACTORY_URL: https://dkregistry.jfrog.io/artifactory/docker/
  ARTIFACTORY_NAME: dkregistry
  ARTIFACTORY_USERNAME: saidinkargedela97@gmail.com
  ARTIFACTORY_PASSWORD: cmVmdGtuOjAxOjE3MjUzNTk0ODU6OUg3UlNJbVFEcVhQS2JYMXVvOHlZZHphYzhu
  CONTAINER_NAME: myimage
    # CLUSTER_NAME: my-aks-cluster
    # CLUSTER_RESOURCE_GROUP: dinkar-rg
    # NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

      # Connecting to Azure Container registry (ACR)
    # - name: ACR Login
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ${{ env.ARTIFACTORY_NAME }}.jfrog.io
    #     username: ${{ secrets.JFROG_USERNAME }} 
    #     password: ${{ secrets.JFROG_PASSWORD }}d
    
    # Docker container build 
    - name: Docker Build
      run: |
        echo '<-----------------------Docker build started----------------------->'
        docker build . -t ${{ env.ARTIFACTORY_NAME }}.jfrog.io/docker/${{env.CONTAINER_NAME}}:${{ github.sha }}
        
        echo '<------------------------Docker build Ended------------------------>'

    # Jfrog Artifactory Login   
    - name: Docker Login
      run: |
        echo '<--------------- Docker Login --------------->'
        docker login ${{ env.ARTIFACTORY_NAME }}.jfrog.io -u ${{ secrets.ARTIFACTORY_USERNAME }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}
        echo '<--------------- Docker Login Ended --------------->'
     
    # Docker Container Push to ACR
    - name: Docker Push
      run: |
        echo '<-----------------------Docker Publish started----------------------->'
        docker tag myimage dkregistry.jfrog.io/docker/${{env.CONTAINER_NAME}}:${{ github.sha }}
        docker push dkregistry.jfrog.io/docker/${{env.CONTAINER_NAME}}:${{ github.sha }}
        echo '<------------------------Docker Publish Ended------------------------>'

