#this pipeline is for python API on Azure Kubernetes Services

name: Build CI

on: push

# Below environment variables available to all jobs and steps in this workflow
env:
    REGISTRY_NAME: sai9356
    CONTAINER_NAME: my-container
    CLUSTER_NAME: my-aks-cluster
    CLUSTER_RESOURCE_GROUP: dinkar-rg
    NAMESPACE: default

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

      # Connecting to Azure Container registry (ACR)
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Docker container build 
    - name: Docker Build
      run: |
        echo '<-----------------------Docker build started----------------------->'
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{env.CONTAINER_NAME}}:${{ github.sha }}
        echo '<------------------------Docker build Ended------------------------>'
    
    # Docker Container Push to ACR
    - name: Docker Push
      run: |
        echo '<-----------------------Docker Publish started----------------------->'
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{env.CONTAINER_NAME}}:${{ github.sha }}
        echo '<------------------------Docker Publish Ended------------------------>'
  
  Deploy:

    runs-on: ubuntu-latest

    needs: [build]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}